dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=stripe setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: ggOpMkJFV4VObYWEkgWDGjKaXSa8zAssKwdesW4vCVzJ/Lv2ul3Es0xSc0WoYQuj9vHXTPz5c87XJw/xzYgGcGXk/EEeAghuBAxMeaR1As3yVdH4ZOFqwJtXH28iv3CJWP/xYAYMmSWh1pMYDavByOmy5s+VvjMvG5Uqv7Pjih9YP07D+jGIsghhzD5/sZpB7bpxbK3CDgcUjAUMnYfkBCabJXyAgz5n6+rk6SBLhs+ZyWI0+VnahtT/Rafk+uRiF8GLKTkVMTdz3EAmDGfzIrETIyo0kw7KU9Jlnbs8s14IwcuFk7y/A/isAuUopGTLRTdDfHemOLWf4VzZkfMvT5b7jaebgZbou1iDvCjS8KwdGlcZJYLxLTGw1ykNdGnnn3YfYXIxi64qGrbxrSJUjlDNGjO0GJXNSWw402lETqJTgtKI71uqqIC7wEtDVSGpgQC9+mAN2SRWZ80r5VOWe4/0wWD2Kk/h/FvNduy+09nzgNF198F07Vhq+w7fDm/R5VuyEmvjnpOcOHgmDrKSgwVi2phbUScz5cNnNi6FgtUP6Z+JKAyszD4eUURlwiKVweTNcaaaPxpztNVgLsRjKIW/Rxaza974l6HDASkVpfBdhg1m83Y3VLrFV/bzECnc/LKeAv3BzYln/E0tJLzUzMqiNEJBFltJVJd6xu6hzo0=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
