sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy2.7-5.9.0"
  - "pypy3.5-5.8.0"
  - "pypy3.5-5.9.0"
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
  - python: 3.8
    dist: xenial
    sudo: true
  - python: pypy
    dist: xenial
    sudo: true
  - python: pypy3
    dist: xenial
    sudo: true
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=stripe setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: ggOpMkJFV4VObYWEkgWDGjKaXSa8zAssKwdesW4vCVzJ/Lv2ul3Es0xSc0WoYQuj9vHXTPz5c87XJw/xzYgGcGXk/EEeAghuBAxMeaR1As3yVdH4ZOFqwJtXH28iv3CJWP/xYAYMmSWh1pMYDavByOmy5s+VvjMvG5Uqv7Pjih9YP07D+jGIsghhzD5/sZpB7bpxbK3CDgcUjAUMnYfkBCabJXyAgz5n6+rk6SBLhs+ZyWI0+VnahtT/Rafk+uRiF8GLKTkVMTdz3EAmDGfzIrETIyo0kw7KU9Jlnbs8s14IwcuFk7y/A/isAuUopGTLRTdDfHemOLWf4VzZkfMvT5b7jaebgZbou1iDvCjS8KwdGlcZJYLxLTGw1ykNdGnnn3YfYXIxi64qGrbxrSJUjlDNGjO0GJXNSWw402lETqJTgtKI71uqqIC7wEtDVSGpgQC9+mAN2SRWZ80r5VOWe4/0wWD2Kk/h/FvNduy+09nzgNF198F07Vhq+w7fDm/R5VuyEmvjnpOcOHgmDrKSgwVi2phbUScz5cNnNi6FgtUP6Z+JKAyszD4eUURlwiKVweTNcaaaPxpztNVgLsRjKIW/Rxaza974l6HDASkVpfBdhg1m83Y3VLrFV/bzECnc/LKeAv3BzYln/E0tJLzUzMqiNEJBFltJVJd6xu6hzo0=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
